blog:
  jwt:
    # 单位毫秒
    expire-in: 86400000
    secret-key: asuqwe124jvst29yr5gslnvui3
  constants:
    page-size: 20
    index-blog-content-text-size: 40
    token-in-header: Authorization
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  security:
    user:
      password: pass
  # 阿里云服务器上的redis
  redis:
    host: 101.201.142.43
    port: 6379
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  offsetAsPageNum: true
  # maybe delete in final version
  page-size-zero: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    name: /logs/my.log
  level:
    root: debug
server:
  port: 8080